# Generated by Django 3.0.5 on 2020-04-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
