# Generated by Django 3.0.5 on 2020-04-24 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
