# Generated by Django 3.0.5 on 2020-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
